import json
import csv
import os
import time
from triage_agent import LLMTriageAgent

def load_ground_truth(csv_path="src/ground_truth.csv"):
    truth_dict = {}
    if not os.path.exists(csv_path):
        print(f"[-] Missing Ground Truth file at {csv_path}")
        return truth_dict

    try:
        with open(csv_path, 'r', encoding='utf-8-sig') as f:
            first_line = f.readline()
            delimiter = ';' if ';' in first_line else ','
    except Exception:
        delimiter = ','

    encodings_to_try = ['utf-8-sig', 'utf-8', 'cp1255', 'windows-1252', 'latin-1']

    for enc in encodings_to_try:
        try:
            with open(csv_path, mode='r', encoding=enc) as f:
                reader = csv.DictReader(f, delimiter=delimiter)

                clean_headers = {}
                if reader.fieldnames:
                    for field in reader.fieldnames:
                        clean_headers[field.strip()] = field

                if 'Rule ID' not in clean_headers or 'Target Class' not in clean_headers:
                    raise KeyError(f"Missing columns in encoding {enc}")

                for row in reader:
                    rule_id = row[clean_headers['Rule ID']].strip()
                    file_and_line = row[clean_headers['Target File & Line']].strip()
                    target_class = row[clean_headers['Target Class']].strip().upper()

                    expected_patch = ""
                    if 'Expected Patch' in clean_headers:
                        expected_patch = row[clean_headers['Expected Patch']].strip()

                    affected_code = ""
                    if 'Affected Code' in clean_headers:
                        affected_code = row[clean_headers['Affected Code']].strip()

                    key = f"{rule_id}|{file_and_line}"
                    
                    truth_dict[key] = {
                        "classification": target_class,
                        "expected_patch": expected_patch,
                        "affected_code": affected_code
                    }
            return truth_dict

        except UnicodeDecodeError:
            continue
        except KeyError:
            continue

    print("[-] Failed to read CSV with all attempted encodings.")
    return truth_dict


def run_evaluation():
    print("[*] Starting Phase 2: Context-Aware Patch Generation (Multi-Agent System)...")

    with open('src/models.json', 'r') as f:
        models_to_test = json.load(f)["models"]

    ground_truth = load_ground_truth()
    if not ground_truth:
        return

    # סינון: ניקח רק את מה שהוא TP
    test_subset = []
    for key, data in ground_truth.items():
        if data["classification"] != 'TP':
            continue  # מדלגים על כל מה שהוא FP

        rule_id, file_and_line = key.split('|', 1)
        if ':' in file_and_line:
            file_path, line_num = file_and_line.split(':', 1)
        else:
            file_path, line_num = file_and_line, "0"

        mock_finding = {
            "rule_id": rule_id,
            "target_file": file_path,
            "line_start": line_num,
            "affected_code": data.get("affected_code", "No code provided"),
            "expected_classification": data["classification"],
            "expected_patch": data["expected_patch"]
        }
        test_subset.append(mock_finding)

    print(f"[*] Filtered {len(test_subset)} True Positive findings.")

    # ---------------------------------------------------------
    # THE ORACLE PHASE: Gemini writes the security reasoning
    # ---------------------------------------------------------
    print("\n" + "=" * 60)
    print("[*] THE ORACLE: Asking Gemini to generate Security Analysis...")
    print("=" * 60)
    
    oracle_agent = LLMTriageAgent(model_name="gemini/gemini-3.1-flash-lite")
    
    for finding in test_subset:
        print(f"   [>] Gemini is analyzing {finding['rule_id']}...")
        try:
            analysis = oracle_agent.analyze_finding(finding)
            finding['reasoning'] = analysis.get('justification', 'No context generated.')
        except Exception as e:
            finding['reasoning'] = f"Oracle failed to analyze: {e}"
        time.sleep(2) 

    # ---------------------------------------------------------
    # THE PATCHING PHASE: All models fix the code using Gemini's context
    # ---------------------------------------------------------
    report_path = "hydroad_multi_agent_patch_report.txt"

    with open(report_path, "w", encoding="utf-8") as report_file:
        report_file.write("=" * 80 + "\n")
        report_file.write("        HYDROAD - MULTI-AGENT PATCH GENERATION REPORT\n")
        report_file.write("        (Security Context generated by Gemini Flash-Lite)\n")
        report_file.write("=" * 80 + "\n\n")

        for model_name in models_to_test:
            print("\n" + "=" * 60)
            print(f"[*] Evaluating Patch Generation: {model_name}")
            print("=" * 60)

            report_file.write(f"### MODEL: {model_name} ###\n\n")

            agent = LLMTriageAgent(model_name=model_name)
            request_counter = 0

            for finding in test_subset:
                request_counter += 1
                
                if "70b" not in model_name and request_counter % 5 == 0:
                    print(f"[*] Rate Limit protection active. Waiting 15 seconds (Request #{request_counter})...")
                    time.sleep(15)

                print(f"      [*] Generating patch for {finding['rule_id']}...")
                
                # --- מדידת הזמנים מתחילה כאן ---
                start_time = time.time()
                patch_response = agent.generate_patch(finding)
                end_time = time.time()
                
                generation_time = end_time - start_time
                print(f"          [+] Done in {generation_time:.2f} seconds.")
                # --- מדידת הזמנים מסתיימת כאן ---
                
                model_fix = patch_response.get("fixed_code", "No code provided.")
                model_strategy = patch_response.get("patch_strategy", "No strategy provided.")

                report_file.write(f"Vulnerability: {finding['rule_id']}\n")
                report_file.write(f"Location:      {finding['target_file']}:{finding['line_start']}\n")
                report_file.write("-" * 80 + "\n")
                report_file.write("[GEMINI'S SECURITY ANALYSIS (CONTEXT PROVIDED TO MODEL)]\n")
                report_file.write(f"{finding['reasoning']}\n\n")
                report_file.write("[EXPECTED STRATEGY - GROUND TRUTH]\n")
                report_file.write(f"{finding['expected_patch']}\n\n")
                report_file.write("[MODEL'S PROPOSED STRATEGY]\n")
                report_file.write(f"{model_strategy}\n\n")
                report_file.write("[MODEL'S GENERATED CODE FIX]\n")
                report_file.write(f"{model_fix}\n\n")
                # הדפסת הזמן שנדרש למודל לענות
                report_file.write(f"[RESPONSE TIME]\n{generation_time:.2f} seconds\n")
                report_file.write("=" * 80 + "\n\n")

            report_file.write("*" * 80 + "\n\n")

    print(f"\n[+] Multi-Agent benchmarking complete! Textual report saved to: {report_path}")

if __name__ == "__main__":
    run_evaluation()
