import os
import json
import time
from litellm import completion


class LLMTriageAgent:
    """
    Orchestrates LLM evaluation of Semgrep findings using LiteLLM.
    Enforces structural JSON output for automated comparative analysis.
    """

    def __init__(self, model_name="gemini/gemini-1.5-pro"):
        self.model_name = model_name

    def generate_patch(self, finding):
        """
        Takes a confirmed True Positive finding and tasks the LLM with writing
        secure, functional remediation code without breaking existing logic.
        """
        system_prompt = """
        You are a Senior Cloud DevSecOps Engineer.
        Your task is to Remediate (fix) a confirmed security vulnerability.

        RULES:
        1. Provide the EXACT lines of code to replace the vulnerable lines.
        2. Ensure the Principle of Least Privilege.
        3. DO NOT break the application's core functionality (e.g., if it's a database connection, keep it working but secure it).

        Respond ONLY with a JSON object matching this schema:
        {
            "patch_strategy": "Brief explanation of how the patch fixes the issue.",
            "original_code": "The exact snippet of vulnerable code you are replacing.",
            "fixed_code": "The secure code ready to be injected."
        }
        """

        user_prompt = f"Vulnerability to Patch:\n{json.dumps(finding, indent=2)}"

        try:
            max_retries = 3
            response = None
            
            for attempt in range(max_retries):
                try:
                    response = completion(
                        model=self.model_name,
                        messages=[
                            {"role": "system", "content": system_prompt},
                            {"role": "user", "content": user_prompt}
                        ],
                        timeout=30  # מנתק את הבקשה אם השרת נתקע ליותר מ-30 שניות
                    )
                    break  # אם הצלחנו, יוצאים מלולאת הניסיונות
                    
                except Exception as api_error:
                    if attempt == max_retries - 1:
                        raise api_error  # אם זה הניסיון האחרון - זורקים את השגיאה החוצה
                    print(f"      [!] API Error ({type(api_error).__name__}). Retrying ({attempt+1}/{max_retries}) in 5 seconds...")
                    time.sleep(5)  # המתנה קלה לפני הניסיון הבא כדי שהשרת יתאושש

            raw_content = response.choices[0].message.content.strip()
            if raw_content.startswith("```json"):
                raw_content = raw_content.replace("```json", "").replace("```", "").strip()
            elif raw_content.startswith("```"):
                raw_content = raw_content.replace("```", "").strip()

            return json.loads(raw_content)
        except Exception as e:
            return {"patch_strategy": "ERROR", "original_code": "", "fixed_code": str(e)}

    def analyze_finding(self, finding):
        """
        Submits a single parsed vulnerability finding to the configured LLM.
        :param finding: Dictionary containing rule_id, target_file, affected_code, etc.
        :return: Parsed JSON response from the model containing classification and reasoning.
        """
        system_prompt = """
        You are an expert Application Security and Cloud Infrastructure (IaC) QA Engineer.
        Your task is to triage security alerts generated by static analysis tools (Semgrep).

        Analyze the provided context and determine if the alert is a:
        1. True Positive (TP): An actual vulnerability or dangerous misconfiguration that poses an operational risk in production.
        2. False Positive (FP): An alert that poses no real danger (e.g., inside test folders, setup scripts, or due to a framework mismatch).

        CRITICAL EVALUATION CRITERIA:
        - Analyze the 'target_file' path. If it is a development tool, seed script, or mock test, it is likely an FP.
        - Examine the 'affected_code' and surrounding lines marked with '>>'. Check for dynamic input flow.

        You MUST respond with a raw JSON object ONLY. Do not wrap the response in markdown blocks like ```json.
        The JSON schema must strictly match:
        {
            "classification": "TP" or "FP",
            "justification": "A definitive, highly technical engineering explanation for your decision.",
            "remedial_patch": "If TP, provide a concise code/configuration fix. If FP, leave empty."
        }
        """

        user_prompt = f"Semgrep Finding to Triage:\n{json.dumps(finding, indent=2)}"

        try:
            max_retries = 3
            response = None
            
            for attempt in range(max_retries):
                try:
                    # Execute the multi-provider abstraction layer via LiteLLM
                    response = completion(
                        model=self.model_name,
                        messages=[
                            {"role": "system", "content": system_prompt},
                            {"role": "user", "content": user_prompt}
                        ],
                        timeout=30  # מנתק את הבקשה אם השרת נתקע ליותר מ-30 שניות
                    )
                    break  # אם הצלחנו, יוצאים מלולאת הניסיונות
                    
                except Exception as api_error:
                    if attempt == max_retries - 1:
                        raise api_error  # אם זה הניסיון האחרון - זורקים את השגיאה החוצה
                    print(f"      [!] API Error ({type(api_error).__name__}). Retrying ({attempt+1}/{max_retries}) in 5 seconds...")
                    time.sleep(5)  # המתנה קלה לפני הניסיון הבא כדי שהשרת יתאושש


            raw_content = response.choices[0].message.content.strip()

            # Clean potential LLM markdown leaks safely
            if raw_content.startswith("```json"):
                raw_content = raw_content.replace("```json", "").replace("```", "").strip()
            elif raw_content.startswith("```"):
                raw_content = raw_content.replace("```", "").strip()

            return json.loads(raw_content)

        except Exception as e:
            return {
                "classification": "ERROR",
                "justification": f"LiteLLM invocation pipeline failed: {str(e)}",
                "remedial_patch": ""
            }