import os
import json
import time
from litellm import completion


class LLMTriageAgent:
    """
    Orchestrates LLM evaluation of Semgrep findings using LiteLLM.
    Enforces structural JSON output for automated comparative analysis.
    """

    def __init__(self, model_name="gemini/gemini-1.5-pro"):
        self.model_name = model_name

    def generate_patch(self, finding):
        """
        Takes a confirmed True Positive finding and tasks the LLM with writing
        secure, functional remediation code without breaking existing logic.
        """
        system_prompt = """
        You are a Senior Cloud DevSecOps Engineer.
        Your task is to Remediate (fix) a confirmed security vulnerability.

        RULES:
        1. Provide the EXACT lines of code to replace the vulnerable lines.
        2. Ensure the Principle of Least Privilege.
        3. DO NOT break the application's core functionality (e.g., if it's a database connection, keep it working but secure it).

        Respond ONLY with a JSON object matching this schema:
        {
            "patch_strategy": "Brief explanation of how the patch fixes the issue.",
            "original_code": "The exact snippet of vulnerable code you are replacing.",
            "fixed_code": "The secure code ready to be injected."
        }
        """

        user_prompt = f"""
        Vulnerability (Rule ID): {finding.get('rule_id')}
        File Location: {finding.get('target_file')}:{finding.get('line_start')}

        --- AFFECTED CODE ---
        {finding.get('affected_code', 'No code provided')}

        --- SECURITY TEAM ANALYSIS (YOUR INSTRUCTIONS) ---
        {finding.get('reasoning', 'No reasoning provided')}
        --------------------------------------------------

        Based on the explicit analysis and instructions above, provide the JSON response with the patch strategy and fixed code.
        """

        try:
            max_retries = 3
            response = None

            for attempt in range(max_retries):
                try:
                    response = completion(
                        model=self.model_name,
                        messages=[
                            {"role": "system", "content": system_prompt},
                            {"role": "user", "content": user_prompt}
                        ],
                        response_format={"type": "json_object"},
                        timeout=30
                    )
                    break

                except Exception as api_error:
                    if attempt == max_retries - 1:
                        raise api_error
                    print(
                        f"      [!] API Error ({type(api_error).__name__}). Retrying ({attempt + 1}/{max_retries}) in 5 seconds...")
                    time.sleep(5)

            raw_content = response.choices[0].message.content.strip()

            raw_content = raw_content.replace("```json", "").replace("```", "").strip()

            return json.loads(raw_content)

        except Exception as e:
            return {"patch_strategy": "ERROR", "original_code": "", "fixed_code": str(e)}

    def analyze_finding(self, finding):
        """
        Submits a single parsed vulnerability finding to the configured LLM.
        """
        system_prompt = """
        You are an expert Application Security Engineer specializing in source code vulnerability analysis.
        Your task is to triage software security alerts generated by the Semgrep SAST scanner.

        Each finding includes the suspicious code snippet, its file path, the relevant CWE (Common Weakness Enumeration),
        OWASP Top 10 category, 'vulnerability_class', 'category', 'technology', and the scanner's own impact and confidence ratings.
        Additionally, if available, it includes 'dataflow_trace', 'metavars' (to show tainted variables), and a suggested 'semgrep_fix'.

        Your goal is to determine whether the alert is a:
        1. True Positive (TP): A real, exploitable vulnerability — e.g., unsanitized user input reaching a dangerous sink
           (SQL query, shell command, file path, eval, HTTP response, etc.) in a code path reachable in production.
        2. False Positive (FP): An alert that poses no real-world risk — e.g., the code is inside a test file, the input
           is hardcoded/controlled, the sink is properly sanitized, or the CWE/OWASP category doesn't apply given the
           actual code context.

        CRITICAL EVALUATION CRITERIA (apply in order):
        - STEP 1 — File Context & Technology: If 'target_file' path contains test/, tests/, seed, mock, fixture, or dev-only scripts,
          it is very likely an FP. Apply stricter scrutiny. Also consider the listed 'technology' stack.
        - STEP 2 — Data Flow & Mechanics: Use the 'dataflow_trace' and 'metavars' fields (if present) alongside the code context 
          to trace whether user-controlled input flows through to a dangerous sink without proper validation or encoding. If no taint path exists, it is likely an FP.
        - STEP 3 — Threat Modeling: Use 'vulnerability_class', 'category', 'cwe', and 'owasp' to understand the class of weakness.
          Reference the standard definition to validate whether the code pattern actually matches the described vulnerability.
        - STEP 4 — Scanner Confidence: Use the 'confidence' and 'impact' fields as weighted signals. HIGH confidence +
          HIGH impact strongly suggests TP. LOW confidence + LOW impact requires clear taint evidence before classifying as TP.
        You MUST respond with a raw JSON object ONLY. Do not wrap the response in markdown blocks like ```json.
        The JSON schema must strictly match:
        {
            "classification": "TP" or "FP",
            "justification": "A definitive, highly technical security engineering explanation for your decision, referencing the CWE/OWASP context and data flow analysis.",
            "remedial_patch": "If TP, provide a concise and secure code fix that mitigates the root cause. If FP, leave empty."
        }
        """

        user_prompt = f"Semgrep Finding to Triage:\n{json.dumps(finding, indent=2)}"

        try:
            max_retries = 3
            response = None

            for attempt in range(max_retries):
                try:
                    response = completion(
                        model=self.model_name,
                        messages=[
                            {"role": "system", "content": system_prompt},
                            {"role": "user", "content": user_prompt}
                        ],
                        timeout=30
                    )
                    break

                except Exception as api_error:
                    if attempt == max_retries - 1:
                        raise api_error
                    print(
                        f"      [!] API Error ({type(api_error).__name__}). Retrying ({attempt + 1}/{max_retries}) in 5 seconds...")
                    time.sleep(5)

            raw_content = response.choices[0].message.content.strip()

            if raw_content.startswith("```json"):
                raw_content = raw_content.replace("```json", "").replace("```", "").strip()
            elif raw_content.startswith("```"):
                raw_content = raw_content.replace("```", "").strip()

            return json.loads(raw_content)

        except Exception as e:
            return {
                "classification": "ERROR",
                "justification": f"LiteLLM invocation pipeline failed: {str(e)}",
                "remedial_patch": ""
            }